### ISSUE TITLE
mobf fails to load causing minetest to fail in start up.

### ISSUE THREAD

**Issue by enkidu-smith** [sapier/animals_modpack#117]
I'm trying to install the Animals Modpack and failing. I've got the zip file in the right place on the server, I believe, but mobf throws the following error. I'm probably missing something as I haven't been running minetest for long. The only other mod that I have is "torches". I don't have a GUI on the server that runs minetest, so I'm activating it via the world's world.mt file.

The server is running on Ubuntu 15.10 (4.2.0-34).
Minetest is 0.4.12 (via PPA).
The Animals Modpack is 2.5.0.

Any ideas? 

Cheers,

Cliff

```
21:02:41: ACTION[main]: MOD: mobf loading ...
21:02:41: ERROR[main]: ========== ERROR FROM LUA ===========
21:02:41: ERROR[main]: Failed to load and run script from 
21:02:41: ERROR[main]: /var/games/minetest-server/.minetest/mods/animals_modpack/mobf/init.lua:
21:02:41: ERROR[main]: ...t-server/.minetest/mods/animals_modpack/mobf/lifebar.lua:21: attempt to call field 'global_exists' 
(a nil value)
21:02:41: ERROR[main]: stack traceback:
21:02:41: ERROR[main]:  ...t-server/.minetest/mods/animals_modpack/mobf/lifebar.lua:21: in main chunk
21:02:41: ERROR[main]:  [C]: in function 'dofile'
21:02:41: ERROR[main]:  ...test-server/.minetest/mods/animals_modpack/mobf/init.lua:77: in main chunk
21:02:41: ERROR[main]: ======= END OF ERROR FROM LUA ========
21:02:41: ERROR[main]: Server: Failed to load and run /var/games/minetest-server/.minetest/mods/animals_modpack/mobf/init.lua

```

**Comment by numberZero** [comment]
MT 0.4.12 has no minetest.global_exists function yet (it present in 0.4.13).
MobF 2.5.1 introduced a workaround (broken, but may help anyway).

**Comment by enkidu-smith** [comment]
I see. So I need to get 2.5.1 of modf and replace it in the modpack? Or
remove 2.5.0 from the modpack and add it as a separate mod?

Cheers,

Cliff

**Comment by enkidu-smith** [comment]
Sorry, do I need to get Animals Modpack 2.5.1 and if so, how do I find it,
please?

Cheers,

Cliff

**Comment by numberZero** [comment]
sorry for late answer.
if still interesting, try this: https://github.com/numberZero/mobf_core/archive/patch-1.zip (replace mobf_core with this unpacked)
or update Minetest to more recent version

**Comment by enkidu-smith** [comment]
Thank you and no worries about the delay. I decided instead to go with the
Ubuntu package minetest-mod-mobf (version is 2.3.6-1), which in spite of
the name appears to be a version of the animals modpack. This installs and
starts fine. I have editted the world's world.mt file to activate mobf,
mobf_settings, animalmaterials, and animal_sheep, but I don't see any
sheep! What controls the spawning of the animals?

When I use the /mobf command nothing happens except that I get "issued
command: mobf". /mobf version gives A dialog about the path marker tool and
the version of mobf (2.3.6), but I'm more interested in the spawning.

Cheers,

Cliff

**Comment by numberZero** [comment]
> have edited the world's world.mt file
MT has GUI for that (unless you have a headless server)

> When I use the /mobf command nothing happens
Try wait a bit more, it takes a lot of time to just show the settings window (why? I don’t know)

> What controls the spawning
Nothing except complete enable/disable in the mobf configuration file (in world directory). mobf 2.3.6 uses ABM to spawn sheep so they should eventually appear on the map although that would take some time. Also it uses mapgen-time spawning so you can try to go far away to find them)

Check your log, make sure you have something like «MOBF:registering willow spawn abm callback for mob»

**Comment by numberZero** [comment]
> have edited the world's world.mt file

MT has GUI for that (unless you have a headless server)

> When I use the /mobf command nothing happens

Try wait a bit more, it takes a lot of time to just show the settings window (why? I don’t know)

> What controls the spawning

Nothing except complete enable/disable in the mobf configuration file (in world directory). mobf 2.3.6 uses ABM to spawn sheep so they should eventually appear on the map although that would take some time (about of 4 hours for one sheep in an ideal _active_ [i.e. near player] chunk).

Also it uses mapgen-time spawning so you can try to go far away to find them)

Check your log file, make sure you have something like “MOBF: registering willow spawn abm callback for mob ...”

**Comment by enkidu-smith** [comment]
Hi thanks for that.

I went out into the wop wops and there were my sheep! Yay! Thank you so
much.

(BTW, my server IS headless!)

Cheers,

Cliff

**Comment by enkidu-smith** [comment]
Thanks, solved.
