### ISSUE TITLE
GPL-2 license block in clownfish.blend

### ISSUE THREAD

**Issue by SnarkBoojum** [sapier/animals_modpack#133]
Hi,

during the review process for my Debian package a GPL-2 license block was found in clownfish.blend ; what is it here for?

Thanks,

Snark on #debian-games

**Comment by SnarkBoojum** [comment]
Hi,

my package is still stuck out of Debian for this license question : can we settle it?

Thanks,

Snark on #debian-games

**Comment by sapier** [comment]
A GPL License block in clownfish.blend? are you sure about it? clownfish.blend is a blender model file I did create myself. It's a binary format and I cannot change it manually. Using a hex editor I don't see any gpl references too.
If debian ppl don't like it just remove it from your package it's not required for playing at all. Sole purpose of this file is to enable ppl to create their own models based on my (unskilled) work.

**Comment by SnarkBoojum** [comment]
There is a GPL license block in clownfish.blend ; if you use "strings clownfish.blend", you'll find it more easily.

I'm supposed to ship the sources, and I think the .blend files are the sources of the .b3d files... do you have any clue why that single .blend file got a GPL fragment?

Thanks,

Snark on #debian-games

**Comment by sapier** [comment]
Ok found it. Seems like blender projects may contain embedded python code for some transformations.
Btw why is gpl a problem for debian?

**Comment by SnarkBoojum** [comment]
The GPL isn't a problem for Debian ; it's the fact that the animals modpack is supposed to be CC-BY-SA 3.0, but there is a GPL block within : Debian is quite serious about getting licensing right.

The fact that it's the only .blend file with such a license block is strange : do you have any clue why that is so?

**Comment by SnarkBoojum** [comment]
Ok, the package went in with those explanations : thanks!
