### ISSUE TITLE
Request a simplified engine to create mobs

### ISSUE THREAD

**Issue by BrunoMine** [sapier/animals_modpack#134]
I realized that this project is focused on bringing together a large number of creatures, but I believe it is to have a base engine of creation that simplifies everything.

I refer to functions and methods of creation. This can be interesting to improve many easily mobs (if all are working on the same engine).

**Comment by sapier** [comment]
nope actually mobf was intended as exactly the engine you do request. Yet most ppl suffer of "not invented here syndrom" thus not using all the existing stuff (movement gens, spawn algorithms fighting ...) and just adding their new features.
