### ISSUE TITLE
[Patch] mob_bear: Check for 'factions' Mod Path

### ISSUE THREAD

**Issue by AntumDeluge** [sapier/animals_modpack#135]
Want to suggest the following patch:

[animals_modpack__mob_bear__init.lua.diff.zip](https://github.com/sapier/animals_modpack/files/416085/animals_modpack__mob_bear__init.lua.diff.zip)
- Uses check for 'minetest.get_modpath("factions")' before referencing global variable 'factions'
    - Removes warning about undeclared global variable

**Comment by sapier** [comment]
merged a little bit different but quite similar solution d996d4c94431963323ace48fe23e5e41e48afd0d
